name: wisepick_proxy_server
description: Proxy server for OpenAI-compatible API
version: 0.0.1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.0.0
  http: ^0.13.0
  crypto: ^3.0.2
  puppeteer: ^2.2.0

executables:
  proxy_server: bin/proxy_server.dart